import {
  type Item,
  type ItemKind,
  type Material,
  type Vec2,
  makeMaterial,
} from '../../types/project'

export type Category =
  | 'Living'
  | 'Bedroom'
  | 'Kitchen'
  | 'Dining'
  | 'Bathroom'
  | 'Office'
  | 'Decor'
  | 'HDB'

export interface CatalogEntry {
  id: string
  kind: ItemKind
  name: string
  category: Category
  size: { w: number; d: number; h: number } // metres, bounding footprint
  material: Material
  params?: Record<string, number | string | boolean>
  baseY?: number // default vertical lift (wall art, range hoods, counter items)
  price?: number // rough S$; falls back to PRICE_BY_KIND
}

// Rough S$ prices by kind, used when an entry has no explicit price. These are
// ballpark figures for a budget estimate, not real quotes.
const PRICE_BY_KIND: Record<ItemKind, number> = {
  sofa: 900,
  bed: 800,
  table: 350,
  chair: 80,
  wardrobe: 650,
  rug: 180,
  lamp: 90,
  cabinet: 300,
  shelf: 250,
  stool: 70,
  tv: 900,
  toilet: 250,
  sink: 350,
  bathtub: 900,
  pendant: 120,
  piano: 4000,
  vase: 60,
  plant: 80,
  picture: 120,
  appliance: 600,
  hood: 450,
  shower: 800,
  toiletries: 40,
  curtain: 150,
  shelter: 0,
  gate: 400,
  glb: 0,
}

export function catalogPrice(entry: CatalogEntry): number {
  return entry.price ?? PRICE_BY_KIND[entry.kind] ?? 100
}

export const CATALOG: CatalogEntry[] = [
  {
    id: 'sofa-3',
    kind: 'sofa',
    name: '3-seat Sofa',
    category: 'Living',
    size: { w: 2.0, d: 0.9, h: 0.8 },
    material: makeMaterial({ color: '#6b7280', roughness: 0.9, texture: 'fabric' }),
  },
  {
    id: 'armchair',
    kind: 'sofa',
    name: 'Armchair',
    category: 'Living',
    size: { w: 0.9, d: 0.9, h: 0.8 },
    material: makeMaterial({ color: '#8a6f5a', roughness: 0.9, texture: 'fabric' }),
    params: { seats: 1 },
  },
  {
    id: 'coffee-table',
    kind: 'table',
    name: 'Coffee Table',
    category: 'Living',
    size: { w: 1.1, d: 0.6, h: 0.4 },
    material: makeMaterial({ color: '#8a5a33', roughness: 0.4, texture: 'wood' }),
  },
  {
    id: 'tv-console',
    kind: 'wardrobe',
    name: 'TV Console',
    category: 'Living',
    size: { w: 1.8, d: 0.4, h: 0.5 },
    material: makeMaterial({ color: '#2b2b2f', roughness: 0.5 }),
    params: { doors: 3 },
  },
  {
    id: 'rug',
    kind: 'rug',
    name: 'Area Rug',
    category: 'Decor',
    size: { w: 2.4, d: 1.6, h: 0.02 },
    material: makeMaterial({ color: '#9c6b52', roughness: 1, texture: 'carpet' }),
  },
  {
    id: 'floor-lamp',
    kind: 'lamp',
    name: 'Floor Lamp',
    category: 'Decor',
    size: { w: 0.4, d: 0.4, h: 1.6 },
    material: makeMaterial({ color: '#d8d2c4', roughness: 0.6, metalness: 0.3 }),
  },
  {
    id: 'plant',
    kind: 'plant',
    name: 'Potted Plant',
    category: 'Decor',
    size: { w: 0.5, d: 0.5, h: 1.1 },
    material: makeMaterial({ color: '#3f7d4f', roughness: 0.9 }),
  },
  {
    id: 'bed-queen',
    kind: 'bed',
    name: 'Queen Bed',
    category: 'Bedroom',
    size: { w: 1.6, d: 2.1, h: 1.0 },
    material: makeMaterial({ color: '#c9c2b6', roughness: 0.95, texture: 'fabric' }),
  },
  {
    id: 'bed-single',
    kind: 'bed',
    name: 'Single Bed',
    category: 'Bedroom',
    size: { w: 0.95, d: 1.95, h: 1.0 },
    material: makeMaterial({ color: '#c9c2b6', roughness: 0.95, texture: 'fabric' }),
  },
  {
    id: 'wardrobe',
    kind: 'wardrobe',
    name: 'Wardrobe',
    category: 'Bedroom',
    size: { w: 1.2, d: 0.6, h: 2.1 },
    material: makeMaterial({ color: '#a9784f', roughness: 0.5, texture: 'wood' }),
    params: { doors: 2 },
  },
  {
    id: 'nightstand',
    kind: 'wardrobe',
    name: 'Nightstand',
    category: 'Bedroom',
    size: { w: 0.45, d: 0.4, h: 0.5 },
    material: makeMaterial({ color: '#a9784f', roughness: 0.5, texture: 'wood' }),
    params: { doors: 1 },
  },
  {
    id: 'dining-table',
    price: 600,
    kind: 'table',
    name: 'Dining Table',
    category: 'Dining',
    size: { w: 1.6, d: 0.9, h: 0.75 },
    material: makeMaterial({ color: '#7a4f2e', roughness: 0.35, texture: 'wood' }),
  },
  {
    id: 'chair',
    kind: 'chair',
    name: 'Dining Chair',
    category: 'Dining',
    size: { w: 0.45, d: 0.5, h: 0.9 },
    material: makeMaterial({ color: '#4b3b2b', roughness: 0.5, texture: 'wood' }),
  },
  {
    id: 'base-cabinet',
    kind: 'cabinet',
    name: 'Base Cabinet',
    category: 'Kitchen',
    size: { w: 0.6, d: 0.6, h: 0.9 },
    material: makeMaterial({ color: '#e8e4dc', roughness: 0.4 }),
    params: { width: 0.6, depth: 0.6, height: 0.9, doors: 2, counter: true },
  },
  {
    id: 'wall-cabinet',
    kind: 'cabinet',
    name: 'Wall Cabinet',
    category: 'Kitchen',
    size: { w: 0.6, d: 0.35, h: 0.7 },
    material: makeMaterial({ color: '#e8e4dc', roughness: 0.4 }),
    params: { width: 0.6, depth: 0.35, height: 0.7, doors: 2, counter: false },
  },
  {
    id: 'corner-cabinet',
    kind: 'cabinet',
    name: 'Corner Cabinet (L)',
    category: 'Kitchen',
    size: { w: 1.0, d: 0.6, h: 0.9 },
    material: makeMaterial({ color: '#e8e4dc', roughness: 0.4 }),
    params: {
      width: 1.0,
      depth: 0.6,
      height: 0.9,
      doors: 1,
      counter: true,
      corner: true,
      legLen: 1.0,
    },
  },
  {
    id: 'fridge',
    price: 1200,
    kind: 'wardrobe',
    name: 'Fridge',
    category: 'Kitchen',
    size: { w: 0.7, d: 0.7, h: 1.8 },
    material: makeMaterial({ color: '#d5d7da', roughness: 0.3, metalness: 0.5 }),
    params: { doors: 2 },
  },

  // --- Living (extra) ---
  {
    id: 'bookshelf',
    kind: 'shelf',
    name: 'Bookshelf',
    category: 'Living',
    size: { w: 0.9, d: 0.3, h: 1.9 },
    material: makeMaterial({ color: '#a9784f', roughness: 0.5, texture: 'wood' }),
    params: { shelves: 4 },
  },
  {
    id: 'tv-55',
    kind: 'tv',
    name: '55" TV',
    category: 'Living',
    size: { w: 1.25, d: 0.3, h: 0.9 },
    material: makeMaterial({ color: '#111214', roughness: 0.4 }),
  },
  {
    id: 'side-table',
    kind: 'table',
    name: 'Side Table',
    category: 'Living',
    size: { w: 0.5, d: 0.5, h: 0.55 },
    material: makeMaterial({ color: '#8a5a33', roughness: 0.4, texture: 'wood' }),
  },

  // --- Bedroom (extra) ---
  {
    id: 'dresser',
    kind: 'wardrobe',
    name: 'Dresser',
    category: 'Bedroom',
    size: { w: 1.1, d: 0.5, h: 0.8 },
    material: makeMaterial({ color: '#a9784f', roughness: 0.5, texture: 'wood' }),
    params: { doors: 3 },
  },
  {
    id: 'vanity-stool',
    kind: 'stool',
    name: 'Stool',
    category: 'Bedroom',
    size: { w: 0.4, d: 0.4, h: 0.45 },
    material: makeMaterial({ color: '#c9c2b6', roughness: 0.9, texture: 'fabric' }),
  },

  // --- Dining (extra) ---
  {
    id: 'bar-stool',
    kind: 'stool',
    name: 'Bar Stool',
    category: 'Dining',
    size: { w: 0.4, d: 0.4, h: 0.75 },
    material: makeMaterial({ color: '#2b2b2f', roughness: 0.5, metalness: 0.3 }),
  },
  {
    id: 'sideboard',
    kind: 'cabinet',
    name: 'Sideboard',
    category: 'Dining',
    size: { w: 1.4, d: 0.45, h: 0.8 },
    material: makeMaterial({ color: '#7a4f2e', roughness: 0.4, texture: 'wood' }),
    params: { width: 1.4, depth: 0.45, height: 0.8, doors: 3, counter: false },
  },

  // --- Kitchen (extra) ---
  {
    id: 'kitchen-sink',
    kind: 'sink',
    name: 'Sink Unit',
    category: 'Kitchen',
    size: { w: 0.8, d: 0.6, h: 0.9 },
    material: makeMaterial({ color: '#e8e4dc', roughness: 0.4 }),
    params: { counter: true },
  },
  {
    id: 'stove',
    kind: 'wardrobe',
    name: 'Oven / Stove',
    category: 'Kitchen',
    size: { w: 0.6, d: 0.6, h: 0.9 },
    material: makeMaterial({ color: '#3a3d42', roughness: 0.4, metalness: 0.4 }),
    params: { doors: 1 },
  },
  {
    id: 'pantry',
    kind: 'wardrobe',
    name: 'Tall Pantry',
    category: 'Kitchen',
    size: { w: 0.6, d: 0.6, h: 2.1 },
    material: makeMaterial({ color: '#e8e4dc', roughness: 0.4 }),
    params: { doors: 2 },
  },

  // --- Bathroom ---
  {
    id: 'toilet',
    kind: 'toilet',
    name: 'Toilet',
    category: 'Bathroom',
    size: { w: 0.4, d: 0.7, h: 0.8 },
    material: makeMaterial({ color: '#f6f6f4', roughness: 0.2 }),
  },
  {
    id: 'bathroom-sink',
    kind: 'sink',
    name: 'Basin Vanity',
    category: 'Bathroom',
    size: { w: 0.6, d: 0.45, h: 0.85 },
    material: makeMaterial({ color: '#e6e2da', roughness: 0.4 }),
    params: { counter: true },
  },
  {
    id: 'bathtub',
    kind: 'bathtub',
    name: 'Bathtub',
    category: 'Bathroom',
    size: { w: 1.7, d: 0.75, h: 0.55 },
    material: makeMaterial({ color: '#f6f6f4', roughness: 0.15 }),
  },

  // --- Office ---
  {
    id: 'desk',
    kind: 'table',
    name: 'Desk',
    category: 'Office',
    size: { w: 1.4, d: 0.7, h: 0.75 },
    material: makeMaterial({ color: '#5a4632', roughness: 0.4, texture: 'wood' }),
  },
  {
    id: 'office-chair',
    kind: 'chair',
    name: 'Office Chair',
    category: 'Office',
    size: { w: 0.6, d: 0.6, h: 1.0 },
    material: makeMaterial({ color: '#2b2b2f', roughness: 0.6 }),
  },
  {
    id: 'bookshelf-tall',
    kind: 'shelf',
    name: 'Tall Shelf',
    category: 'Office',
    size: { w: 0.8, d: 0.3, h: 2.0 },
    material: makeMaterial({ color: '#8a5a33', roughness: 0.5, texture: 'wood' }),
    params: { shelves: 5 },
  },

  // --- Decor (extra) ---
  {
    id: 'pendant-light',
    kind: 'pendant',
    name: 'Pendant Light',
    category: 'Decor',
    size: { w: 0.35, d: 0.35, h: 0.4 },
    material: makeMaterial({ color: '#2b2b2f', roughness: 0.5, metalness: 0.3 }),
  },
  {
    id: 'curtains',
    kind: 'curtain',
    name: 'Curtains',
    category: 'Decor',
    size: { w: 1.6, d: 0.1, h: 2.4 },
    material: makeMaterial({ color: '#cfc6b8', roughness: 0.95, texture: 'fabric' }),
  },
  {
    id: 'blinds',
    kind: 'curtain',
    name: 'Blinds',
    category: 'Decor',
    size: { w: 1.2, d: 0.06, h: 1.3 },
    material: makeMaterial({ color: '#d8d2c4', roughness: 0.7 }),
    params: { blinds: true },
    baseY: 0.9,
  },

  // --- Built-in carpentry ---
  {
    id: 'built-in-wardrobe',
    kind: 'wardrobe',
    name: 'Built-in Wardrobe',
    category: 'Bedroom',
    size: { w: 2.4, d: 0.6, h: 2.4 },
    material: makeMaterial({ color: '#c9b79a', roughness: 0.5, texture: 'wood' }),
    params: { doors: 4 },
    price: 2500,
  },
  {
    id: 'kitchen-island',
    kind: 'cabinet',
    name: 'Kitchen Island',
    category: 'Kitchen',
    size: { w: 1.6, d: 0.9, h: 0.9 },
    material: makeMaterial({ color: '#e8e4dc', roughness: 0.4 }),
    params: { width: 1.6, depth: 0.9, height: 0.9, doors: 3, counter: true },
    price: 2000,
  },

  // ===== Living (more) =====
  {
    id: 'loveseat',
    kind: 'sofa',
    name: 'Loveseat',
    category: 'Living',
    size: { w: 1.5, d: 0.9, h: 0.8 },
    material: makeMaterial({ color: '#7a8a7c', roughness: 0.9, texture: 'fabric' }),
    params: { seats: 2 },
  },
  {
    id: 'sectional-sofa',
    price: 1600,
    kind: 'sofa',
    name: 'L-Sectional Sofa',
    category: 'Living',
    size: { w: 2.5, d: 1.6, h: 0.8 },
    material: makeMaterial({ color: '#59606b', roughness: 0.9, texture: 'fabric' }),
    params: { chaise: true },
  },
  {
    id: 'piano',
    price: 4500,
    kind: 'piano',
    name: 'Upright Piano',
    category: 'Living',
    size: { w: 1.5, d: 0.62, h: 1.2 },
    material: makeMaterial({ color: '#17181b', roughness: 0.25, metalness: 0.1 }),
  },
  {
    id: 'floor-vase',
    kind: 'vase',
    name: 'Floor Vase',
    category: 'Living',
    size: { w: 0.32, d: 0.32, h: 0.7 },
    material: makeMaterial({ color: '#b7724a', roughness: 0.4 }),
  },
  {
    id: 'wall-art-l',
    kind: 'picture',
    name: 'Wall Art (large)',
    category: 'Living',
    size: { w: 1.2, d: 0.05, h: 0.8 },
    material: makeMaterial({ color: '#6d84a8', roughness: 0.7 }),
    baseY: 1.15,
  },
  {
    id: 'wall-art-set',
    kind: 'picture',
    name: 'Framed Print',
    category: 'Living',
    size: { w: 0.55, d: 0.05, h: 0.75 },
    material: makeMaterial({ color: '#c58a5a', roughness: 0.7 }),
    baseY: 1.3,
  },
  {
    id: 'table-lamp',
    kind: 'lamp',
    name: 'Table Lamp',
    category: 'Living',
    size: { w: 0.3, d: 0.3, h: 0.5 },
    material: makeMaterial({ color: '#e6ddc9', roughness: 0.6 }),
    baseY: 0.4,
  },

  // ===== Bedroom (more) =====
  {
    id: 'bed-king',
    price: 1200,
    kind: 'bed',
    name: 'King Bed',
    category: 'Bedroom',
    size: { w: 1.9, d: 2.1, h: 1.0 },
    material: makeMaterial({ color: '#b9c3cb', roughness: 0.95, texture: 'fabric' }),
  },
  {
    id: 'bed-double',
    kind: 'bed',
    name: 'Double Bed',
    category: 'Bedroom',
    size: { w: 1.4, d: 2.0, h: 1.0 },
    material: makeMaterial({ color: '#cbb8a6', roughness: 0.95, texture: 'fabric' }),
  },
  {
    id: 'bed-kids',
    kind: 'bed',
    name: 'Kids Bed',
    category: 'Bedroom',
    size: { w: 0.95, d: 1.7, h: 0.85 },
    material: makeMaterial({ color: '#8fb7d6', roughness: 0.95, texture: 'fabric' }),
  },
  {
    id: 'bedroom-plant',
    kind: 'plant',
    name: 'Tall Plant',
    category: 'Bedroom',
    size: { w: 0.6, d: 0.6, h: 1.6 },
    material: makeMaterial({ color: '#3f7d4f', roughness: 0.9 }),
    params: { tall: true },
  },

  // ===== Kitchen appliances =====
  {
    id: 'microwave',
    kind: 'appliance',
    name: 'Microwave',
    category: 'Kitchen',
    size: { w: 0.5, d: 0.36, h: 0.3 },
    material: makeMaterial({ color: '#2c2f34', roughness: 0.4, metalness: 0.3 }),
    baseY: 0.9,
  },
  {
    id: 'dishwasher',
    kind: 'appliance',
    name: 'Dishwasher',
    category: 'Kitchen',
    size: { w: 0.6, d: 0.6, h: 0.85 },
    material: makeMaterial({ color: '#c9ccd0', roughness: 0.3, metalness: 0.5 }),
  },
  {
    id: 'washer',
    kind: 'appliance',
    name: 'Washing Machine',
    category: 'Kitchen',
    size: { w: 0.6, d: 0.6, h: 0.85 },
    material: makeMaterial({ color: '#e7e9ec', roughness: 0.35, metalness: 0.3 }),
    params: { roundDoor: true },
  },
  {
    id: 'range-hood',
    kind: 'hood',
    name: 'Range Hood',
    category: 'Kitchen',
    size: { w: 0.9, d: 0.5, h: 0.6 },
    material: makeMaterial({ color: '#c8ccd0', roughness: 0.3, metalness: 0.6 }),
    baseY: 1.5,
  },
  {
    id: 'coffee-machine',
    kind: 'appliance',
    name: 'Coffee Machine',
    category: 'Kitchen',
    size: { w: 0.3, d: 0.4, h: 0.4 },
    material: makeMaterial({ color: '#3a3d42', roughness: 0.4, metalness: 0.3 }),
    baseY: 0.9,
  },
  {
    id: 'kettle',
    kind: 'appliance',
    name: 'Kettle',
    category: 'Kitchen',
    size: { w: 0.22, d: 0.22, h: 0.26 },
    material: makeMaterial({ color: '#d5d7da', roughness: 0.3, metalness: 0.5 }),
    baseY: 0.9,
  },

  // ===== Bathroom (more) =====
  {
    id: 'shower',
    kind: 'shower',
    name: 'Shower Stall',
    category: 'Bathroom',
    size: { w: 0.9, d: 0.9, h: 2.0 },
    material: makeMaterial({ color: '#dfe6ea', roughness: 0.1, metalness: 0.1 }),
  },
  {
    id: 'mirror',
    kind: 'picture',
    name: 'Mirror',
    category: 'Bathroom',
    size: { w: 0.7, d: 0.04, h: 1.0 },
    material: makeMaterial({ color: '#dfe7ee', roughness: 0.05, metalness: 0.9 }),
    baseY: 1.0,
    params: { mirror: true },
  },
  {
    id: 'toiletries',
    kind: 'toiletries',
    name: 'Toiletries',
    category: 'Bathroom',
    size: { w: 0.3, d: 0.16, h: 0.22 },
    material: makeMaterial({ color: '#8fbfc8', roughness: 0.5 }),
    baseY: 0.9,
  },
  {
    id: 'towel-plant',
    kind: 'plant',
    name: 'Small Plant',
    category: 'Bathroom',
    size: { w: 0.3, d: 0.3, h: 0.5 },
    material: makeMaterial({ color: '#4f9d5f', roughness: 0.9 }),
    baseY: 0.9,
  },

  // ===== Office (more) =====
  {
    id: 'filing-cabinet',
    kind: 'cabinet',
    name: 'Filing Cabinet',
    category: 'Office',
    size: { w: 0.5, d: 0.6, h: 0.7 },
    material: makeMaterial({ color: '#4a4d52', roughness: 0.4, metalness: 0.3 }),
    params: { width: 0.5, depth: 0.6, height: 0.7, doors: 1, counter: false },
  },

  // ===== Decor (more) =====
  {
    id: 'table-vase',
    kind: 'vase',
    name: 'Vase with Flowers',
    category: 'Decor',
    size: { w: 0.2, d: 0.2, h: 0.3 },
    material: makeMaterial({ color: '#d8d2c4', roughness: 0.3 }),
    params: { flowers: true },
    baseY: 0.75,
  },
  {
    id: 'wall-mirror',
    kind: 'picture',
    name: 'Round Mirror',
    category: 'Decor',
    size: { w: 0.7, d: 0.05, h: 0.7 },
    material: makeMaterial({ color: '#dfe7ee', roughness: 0.05, metalness: 0.9 }),
    baseY: 1.2,
    params: { mirror: true, round: true },
  },

  // ===== HDB-specific fixtures =====
  {
    id: 'household-shelter',
    kind: 'shelter',
    name: 'Household Shelter',
    category: 'HDB',
    size: { w: 1.5, d: 1.4, h: 2.4 },
    material: makeMaterial({ color: '#b9bcc0', roughness: 0.9, texture: 'concrete' }),
  },
  {
    id: 'hdb-gate',
    kind: 'gate',
    name: 'Metal Gate',
    category: 'HDB',
    size: { w: 1.0, d: 0.06, h: 2.1 },
    material: makeMaterial({ color: '#3a3f47', roughness: 0.4, metalness: 0.7 }),
  },
  {
    id: 'bay-window-seat',
    kind: 'wardrobe',
    name: 'Bay Window Seat',
    category: 'HDB',
    size: { w: 1.6, d: 0.5, h: 0.5 },
    material: makeMaterial({ color: '#d8cbb2', roughness: 0.5, texture: 'wood' }),
    params: { doors: 3 },
  },
  {
    id: 'aircon-ledge',
    kind: 'wardrobe',
    name: 'Aircon Ledge',
    category: 'HDB',
    size: { w: 1.2, d: 0.55, h: 0.35 },
    material: makeMaterial({ color: '#c7cacd', roughness: 0.8 }),
    params: { doors: 1 },
  },
  {
    id: 'planter-box',
    kind: 'wardrobe',
    name: 'Planter Box',
    category: 'HDB',
    size: { w: 1.0, d: 0.4, h: 0.4 },
    material: makeMaterial({ color: '#7a5a3a', roughness: 0.9 }),
    params: { doors: 1 },
  },

  // ===== Kitchen cabinetry =====
  // Widths follow the usual carcass sizes (300/600/800/900mm) so runs line up.
  {
    id: 'base-cabinet-30',
    kind: 'cabinet',
    name: 'Base Cabinet 300',
    category: 'Kitchen',
    size: { w: 0.3, d: 0.6, h: 0.9 },
    material: makeMaterial({ color: '#e8e4dc', roughness: 0.4 }),
    params: { width: 0.3, depth: 0.6, height: 0.9, doors: 1, counter: true },
    price: 190,
  },
  {
    id: 'base-cabinet-90',
    kind: 'cabinet',
    name: 'Base Cabinet 900',
    category: 'Kitchen',
    size: { w: 0.9, d: 0.6, h: 0.9 },
    material: makeMaterial({ color: '#e8e4dc', roughness: 0.4 }),
    params: { width: 0.9, depth: 0.6, height: 0.9, doors: 2, counter: true },
    price: 420,
  },
  {
    id: 'drawer-base-60',
    kind: 'cabinet',
    name: 'Drawer Base 600',
    category: 'Kitchen',
    size: { w: 0.6, d: 0.6, h: 0.9 },
    material: makeMaterial({ color: '#e8e4dc', roughness: 0.4 }),
    params: { width: 0.6, depth: 0.6, height: 0.9, doors: 1, counter: true, drawers: 3 },
    price: 480,
  },
  {
    id: 'drawer-base-90',
    kind: 'cabinet',
    name: 'Drawer Base 900',
    category: 'Kitchen',
    size: { w: 0.9, d: 0.6, h: 0.9 },
    material: makeMaterial({ color: '#e8e4dc', roughness: 0.4 }),
    params: { width: 0.9, depth: 0.6, height: 0.9, doors: 1, counter: true, drawers: 4 },
    price: 620,
  },
  {
    id: 'sink-base-80',
    kind: 'cabinet',
    name: 'Sink Base 800',
    category: 'Kitchen',
    size: { w: 0.8, d: 0.6, h: 0.9 },
    material: makeMaterial({ color: '#e8e4dc', roughness: 0.4 }),
    params: { width: 0.8, depth: 0.6, height: 0.9, doors: 2, counter: true },
    price: 400,
  },
  {
    id: 'wall-cabinet-90',
    kind: 'cabinet',
    name: 'Wall Cabinet 900',
    category: 'Kitchen',
    size: { w: 0.9, d: 0.35, h: 0.7 },
    material: makeMaterial({ color: '#e8e4dc', roughness: 0.4 }),
    params: { width: 0.9, depth: 0.35, height: 0.7, doors: 2, counter: false },
    baseY: 1.4,
    price: 360,
  },
  {
    id: 'wall-cabinet-tall',
    kind: 'cabinet',
    name: 'Tall Wall Cabinet',
    category: 'Kitchen',
    size: { w: 0.6, d: 0.35, h: 0.9 },
    material: makeMaterial({ color: '#e8e4dc', roughness: 0.4 }),
    params: { width: 0.6, depth: 0.35, height: 0.9, doors: 2, counter: false },
    baseY: 1.25,
    price: 320,
  },
  {
    id: 'open-kitchen-shelves',
    kind: 'shelf',
    name: 'Open Kitchen Shelves',
    category: 'Kitchen',
    size: { w: 0.9, d: 0.28, h: 0.75 },
    material: makeMaterial({ color: '#a9784f', roughness: 0.5, texture: 'wood' }),
    params: { shelves: 3 },
    baseY: 1.4,
    price: 160,
  },
  {
    id: 'tall-larder',
    kind: 'wardrobe',
    name: 'Tall Larder Unit',
    category: 'Kitchen',
    size: { w: 0.9, d: 0.6, h: 2.1 },
    material: makeMaterial({ color: '#e8e4dc', roughness: 0.4 }),
    params: { doors: 2 },
    price: 900,
  },
  {
    id: 'broom-cabinet',
    kind: 'wardrobe',
    name: 'Broom Cabinet',
    category: 'Kitchen',
    size: { w: 0.45, d: 0.6, h: 2.1 },
    material: makeMaterial({ color: '#e8e4dc', roughness: 0.4 }),
    params: { doors: 1 },
    price: 480,
  },

  // ===== Kitchen appliances & worktop accessories =====
  {
    id: 'built-in-oven',
    kind: 'appliance',
    name: 'Built-in Oven',
    category: 'Kitchen',
    size: { w: 0.6, d: 0.56, h: 0.6 },
    material: makeMaterial({ color: '#2b2e33', roughness: 0.35, metalness: 0.5 }),
    baseY: 0.3,
    price: 1100,
  },
  {
    id: 'rice-cooker',
    kind: 'appliance',
    name: 'Rice Cooker',
    category: 'Kitchen',
    size: { w: 0.28, d: 0.32, h: 0.28 },
    material: makeMaterial({ color: '#eceef1', roughness: 0.35, metalness: 0.2 }),
    baseY: 0.9,
    price: 120,
  },
  {
    id: 'air-fryer',
    kind: 'appliance',
    name: 'Air Fryer',
    category: 'Kitchen',
    size: { w: 0.32, d: 0.36, h: 0.34 },
    material: makeMaterial({ color: '#33363b', roughness: 0.4 }),
    baseY: 0.9,
    price: 180,
  },
  {
    id: 'toaster',
    kind: 'appliance',
    name: 'Toaster',
    category: 'Kitchen',
    size: { w: 0.28, d: 0.18, h: 0.2 },
    material: makeMaterial({ color: '#c9ccd0', roughness: 0.3, metalness: 0.5 }),
    baseY: 0.9,
    price: 60,
  },
  {
    id: 'utensil-jar',
    kind: 'vase',
    name: 'Utensil Jar',
    category: 'Kitchen',
    size: { w: 0.14, d: 0.14, h: 0.22 },
    material: makeMaterial({ color: '#b9b2a5', roughness: 0.6 }),
    baseY: 0.9,
    price: 20,
  },
  {
    id: 'kitchen-runner',
    kind: 'rug',
    name: 'Kitchen Runner',
    category: 'Kitchen',
    size: { w: 2.0, d: 0.6, h: 0.02 },
    material: makeMaterial({ color: '#5c6470', roughness: 0.9, texture: 'fabric' }),
    price: 60,
  },

  // ===== Furniture =====
  {
    id: 'recliner',
    kind: 'sofa',
    name: 'Recliner',
    category: 'Living',
    size: { w: 0.95, d: 1.0, h: 1.0 },
    material: makeMaterial({ color: '#57544f', roughness: 0.9, texture: 'fabric' }),
    params: { seats: 1 },
    price: 700,
  },
  {
    id: 'ottoman',
    kind: 'stool',
    name: 'Ottoman',
    category: 'Living',
    size: { w: 0.6, d: 0.6, h: 0.4 },
    material: makeMaterial({ color: '#8c8578', roughness: 0.9, texture: 'fabric' }),
    price: 150,
  },
  {
    id: 'console-table',
    kind: 'table',
    name: 'Console Table',
    category: 'Living',
    size: { w: 1.1, d: 0.35, h: 0.8 },
    material: makeMaterial({ color: '#8a6a48', roughness: 0.5, texture: 'wood' }),
    price: 280,
  },
  {
    id: 'nest-tables',
    kind: 'table',
    name: 'Nest of Tables',
    category: 'Living',
    size: { w: 0.55, d: 0.45, h: 0.45 },
    material: makeMaterial({ color: '#a9784f', roughness: 0.5, texture: 'wood' }),
    price: 160,
  },
  {
    id: 'tv-wall-unit',
    kind: 'cabinet',
    name: 'TV Wall Unit',
    category: 'Living',
    size: { w: 2.4, d: 0.45, h: 0.55 },
    material: makeMaterial({ color: '#3f4348', roughness: 0.5 }),
    params: { width: 2.4, depth: 0.45, height: 0.55, doors: 1, counter: false, drawers: 2 },
    price: 750,
  },
  {
    id: 'shoe-cabinet',
    kind: 'cabinet',
    name: 'Shoe Cabinet',
    category: 'Living',
    size: { w: 0.9, d: 0.35, h: 1.0 },
    material: makeMaterial({ color: '#d9d4cb', roughness: 0.45 }),
    params: { width: 0.9, depth: 0.35, height: 1.0, doors: 1, counter: false, drawers: 3 },
    price: 320,
  },
  {
    id: 'display-cabinet',
    kind: 'shelf',
    name: 'Display Cabinet',
    category: 'Living',
    size: { w: 0.8, d: 0.35, h: 1.8 },
    material: makeMaterial({ color: '#6f5b45', roughness: 0.5, texture: 'wood-dark' }),
    params: { shelves: 5 },
    price: 480,
  },
  {
    id: 'chest-of-drawers',
    kind: 'cabinet',
    name: 'Chest of Drawers',
    category: 'Bedroom',
    size: { w: 0.8, d: 0.45, h: 1.0 },
    material: makeMaterial({ color: '#b08a5f', roughness: 0.5, texture: 'wood' }),
    params: { width: 0.8, depth: 0.45, height: 1.0, doors: 1, counter: false, drawers: 4 },
    price: 420,
  },
  {
    id: 'bedside-drawers',
    kind: 'cabinet',
    name: 'Bedside Drawers',
    category: 'Bedroom',
    size: { w: 0.45, d: 0.4, h: 0.55 },
    material: makeMaterial({ color: '#b08a5f', roughness: 0.5, texture: 'wood' }),
    params: { width: 0.45, depth: 0.4, height: 0.55, doors: 1, counter: false, drawers: 2 },
    price: 180,
  },
  {
    id: 'daybed',
    kind: 'bed',
    name: 'Daybed',
    category: 'Bedroom',
    size: { w: 1.0, d: 2.0, h: 0.5 },
    material: makeMaterial({ color: '#8f9299', roughness: 0.9, texture: 'fabric' }),
    price: 600,
  },
  {
    id: 'cot',
    kind: 'bed',
    name: 'Baby Cot',
    category: 'Bedroom',
    size: { w: 0.7, d: 1.3, h: 0.9 },
    material: makeMaterial({ color: '#efe9df', roughness: 0.5 }),
    price: 350,
  },
  {
    id: 'dining-bench',
    kind: 'stool',
    name: 'Dining Bench',
    category: 'Dining',
    size: { w: 1.4, d: 0.35, h: 0.45 },
    material: makeMaterial({ color: '#a9784f', roughness: 0.5, texture: 'wood' }),
    price: 220,
  },
  {
    id: 'dining-table-6',
    kind: 'table',
    name: 'Dining Table (6)',
    category: 'Dining',
    size: { w: 1.8, d: 0.9, h: 0.75 },
    material: makeMaterial({ color: '#8a6a48', roughness: 0.5, texture: 'wood' }),
    price: 700,
  },
  {
    id: 'round-dining-table',
    kind: 'table',
    name: 'Round Dining Table',
    category: 'Dining',
    size: { w: 1.1, d: 1.1, h: 0.75 },
    material: makeMaterial({ color: '#a9784f', roughness: 0.5, texture: 'wood' }),
    price: 480,
  },
  {
    id: 'bar-table',
    kind: 'table',
    name: 'Bar Table',
    category: 'Dining',
    size: { w: 1.2, d: 0.45, h: 1.05 },
    material: makeMaterial({ color: '#4a4d53', roughness: 0.5 }),
    price: 380,
  },
  {
    id: 'study-desk',
    kind: 'table',
    name: 'Study Desk',
    category: 'Office',
    size: { w: 1.2, d: 0.6, h: 0.75 },
    material: makeMaterial({ color: '#c8b39a', roughness: 0.5, texture: 'wood' }),
    price: 320,
  },
  {
    id: 'drawer-pedestal',
    kind: 'cabinet',
    name: 'Desk Drawers',
    category: 'Office',
    size: { w: 0.4, d: 0.5, h: 0.6 },
    material: makeMaterial({ color: '#d9d4cb', roughness: 0.45 }),
    params: { width: 0.4, depth: 0.5, height: 0.6, doors: 1, counter: false, drawers: 3 },
    price: 200,
  },
  {
    id: 'bathroom-vanity',
    kind: 'cabinet',
    name: 'Bathroom Vanity',
    category: 'Bathroom',
    size: { w: 0.8, d: 0.45, h: 0.8 },
    material: makeMaterial({ color: '#e3ded4', roughness: 0.4 }),
    params: { width: 0.8, depth: 0.45, height: 0.8, doors: 2, counter: true },
    price: 450,
  },
  {
    id: 'bathroom-tall-cabinet',
    kind: 'wardrobe',
    name: 'Tall Bathroom Cabinet',
    category: 'Bathroom',
    size: { w: 0.4, d: 0.35, h: 1.8 },
    material: makeMaterial({ color: '#e3ded4', roughness: 0.4 }),
    params: { doors: 1 },
    price: 300,
  },

  // ===== Accessories =====
  {
    id: 'bath-mat',
    kind: 'rug',
    name: 'Bath Mat',
    category: 'Bathroom',
    size: { w: 0.8, d: 0.5, h: 0.02 },
    material: makeMaterial({ color: '#8fa3ad', roughness: 0.95, texture: 'fabric' }),
    price: 25,
  },
  {
    id: 'laundry-basket',
    kind: 'vase',
    name: 'Laundry Basket',
    category: 'Bathroom',
    size: { w: 0.42, d: 0.42, h: 0.55 },
    material: makeMaterial({ color: '#c2b49b', roughness: 0.8 }),
    price: 40,
  },
  {
    id: 'waste-bin',
    kind: 'vase',
    name: 'Waste Bin',
    category: 'Bathroom',
    size: { w: 0.26, d: 0.26, h: 0.34 },
    material: makeMaterial({ color: '#b9bcc1', roughness: 0.4, metalness: 0.4 }),
    price: 30,
  },
  {
    id: 'wall-clock',
    kind: 'picture',
    name: 'Wall Clock',
    category: 'Decor',
    size: { w: 0.32, d: 0.04, h: 0.32 },
    material: makeMaterial({ color: '#f0ece4', roughness: 0.5 }),
    params: { round: true },
    baseY: 1.6,
    price: 45,
  },
  {
    id: 'gallery-wall',
    kind: 'picture',
    name: 'Gallery Wall Set',
    category: 'Decor',
    size: { w: 1.4, d: 0.04, h: 0.9 },
    material: makeMaterial({ color: '#2f3238', roughness: 0.5 }),
    baseY: 1.15,
    price: 180,
  },
  {
    id: 'full-length-mirror',
    kind: 'picture',
    name: 'Full-length Mirror',
    category: 'Decor',
    size: { w: 0.55, d: 0.05, h: 1.6 },
    material: makeMaterial({ color: '#cfd6dd', roughness: 0.1, metalness: 0.6 }),
    params: { mirror: true },
    baseY: 0.1,
    price: 160,
  },
  {
    id: 'umbrella-stand',
    kind: 'vase',
    name: 'Umbrella Stand',
    category: 'Decor',
    size: { w: 0.24, d: 0.24, h: 0.5 },
    material: makeMaterial({ color: '#6d7480', roughness: 0.5, metalness: 0.3 }),
    price: 45,
  },
  {
    id: 'table-plant-small',
    kind: 'plant',
    name: 'Small Table Plant',
    category: 'Decor',
    size: { w: 0.22, d: 0.22, h: 0.32 },
    material: makeMaterial({ color: '#7c8b5f', roughness: 0.8 }),
    baseY: 0.75,
    price: 30,
  },
  {
    id: 'tall-planter',
    kind: 'plant',
    name: 'Tall Planter',
    category: 'Decor',
    size: { w: 0.5, d: 0.5, h: 1.7 },
    material: makeMaterial({ color: '#6f7f56', roughness: 0.8 }),
    params: { tall: true },
    price: 140,
  },
  {
    id: 'runner-rug',
    kind: 'rug',
    name: 'Hallway Runner',
    category: 'Decor',
    size: { w: 2.4, d: 0.8, h: 0.02 },
    material: makeMaterial({ color: '#7a5f52', roughness: 0.9, texture: 'fabric' }),
    price: 120,
  },
  {
    id: 'round-rug',
    kind: 'rug',
    name: 'Round Rug',
    category: 'Decor',
    size: { w: 1.6, d: 1.6, h: 0.02 },
    material: makeMaterial({ color: '#9c8f7a', roughness: 0.9, texture: 'fabric' }),
    params: { round: true },
    price: 190,
  },
  {
    id: 'desk-lamp',
    kind: 'lamp',
    name: 'Desk Lamp',
    category: 'Office',
    size: { w: 0.16, d: 0.16, h: 0.42 },
    material: makeMaterial({ color: '#3d4046', roughness: 0.4, metalness: 0.3 }),
    baseY: 0.75,
    price: 55,
  },
  {
    id: 'arc-floor-lamp',
    kind: 'lamp',
    name: 'Arc Floor Lamp',
    category: 'Decor',
    size: { w: 0.3, d: 0.3, h: 1.9 },
    material: makeMaterial({ color: '#2f3238', roughness: 0.4, metalness: 0.4 }),
    price: 190,
  },
]

export const CATEGORIES: Category[] = [
  'Living',
  'Bedroom',
  'Kitchen',
  'Dining',
  'Bathroom',
  'Office',
  'Decor',
  'HDB',
]

export function catalogById(id: string): CatalogEntry | undefined {
  return CATALOG.find((c) => c.id === id)
}

/** Build a placeable Item (minus id) from a catalog entry at a floor position. */
export function newItemFromCatalog(entry: CatalogEntry, pos: Vec2): Omit<Item, 'id'> {
  // wall cabinets float above the counter; pendants hang near the ceiling
  let y = 0
  if (typeof entry.baseY === 'number') y = entry.baseY
  else if (entry.id === 'wall-cabinet') y = 1.4
  else if (entry.kind === 'pendant') y = 2.3
  return {
    catalogId: entry.id,
    kind: entry.kind,
    name: entry.name,
    position: { ...pos },
    y,
    rotationY: 0,
    scale: 1,
    material: { ...entry.material },
    params: entry.params ? { ...entry.params } : undefined,
  }
}
